"""add player_season_info table

Revision ID: 54b174c89a37
Revises: d8e2e8a9a71d
Create Date: 2025-04-16 09:35:09.393524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b174c89a37'
down_revision = 'd8e2e8a9a71d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_info',
    sa.Column('season_info_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('injury_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('season_info_id')
    )
    op.create_index(op.f('ix_player_season_info_player_id'), 'player_season_info', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_info_season_info_id'), 'player_season_info', ['season_info_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_season_info_season_info_id'), table_name='player_season_info')
    op.drop_index(op.f('ix_player_season_info_player_id'), table_name='player_season_info')
    op.drop_table('player_season_info')
    # ### end Alembic commands ###
