"""Add advanced stats columns to player_stats

Revision ID: 91d7e3b74719
Revises: 54b174c89a37
Create Date: 2025-05-28 09:18:02.295517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d7e3b74719'
down_revision = '54b174c89a37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('usage_rate', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('true_shooting_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('effective_fg_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('player_efficiency_rating', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('points_per_36', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('rebounds_per_36', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('assists_per_36', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('steals_per_36', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('blocks_per_36', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('turnovers_per_36', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('three_point_attempt_rate', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('free_throw_rate', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('offensive_rebound_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('defensive_rebound_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('total_rebound_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('assist_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('steal_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('block_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('turnover_pct', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('offensive_win_shares', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('defensive_win_shares', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('win_shares', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('win_shares_per_48', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('box_plus_minus', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('value_over_replacement', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'value_over_replacement')
    op.drop_column('player_stats', 'box_plus_minus')
    op.drop_column('player_stats', 'win_shares_per_48')
    op.drop_column('player_stats', 'win_shares')
    op.drop_column('player_stats', 'defensive_win_shares')
    op.drop_column('player_stats', 'offensive_win_shares')
    op.drop_column('player_stats', 'turnover_pct')
    op.drop_column('player_stats', 'block_pct')
    op.drop_column('player_stats', 'steal_pct')
    op.drop_column('player_stats', 'assist_pct')
    op.drop_column('player_stats', 'total_rebound_pct')
    op.drop_column('player_stats', 'defensive_rebound_pct')
    op.drop_column('player_stats', 'offensive_rebound_pct')
    op.drop_column('player_stats', 'free_throw_rate')
    op.drop_column('player_stats', 'three_point_attempt_rate')
    op.drop_column('player_stats', 'turnovers_per_36')
    op.drop_column('player_stats', 'blocks_per_36')
    op.drop_column('player_stats', 'steals_per_36')
    op.drop_column('player_stats', 'assists_per_36')
    op.drop_column('player_stats', 'rebounds_per_36')
    op.drop_column('player_stats', 'points_per_36')
    op.drop_column('player_stats', 'player_efficiency_rating')
    op.drop_column('player_stats', 'effective_fg_pct')
    op.drop_column('player_stats', 'true_shooting_pct')
    op.drop_column('player_stats', 'usage_rate')
    op.drop_column('player_stats', 'age')
    # ### end Alembic commands ###
