"""create PlayerStats table

Revision ID: 93bbb72f6865
Revises: 
Create Date: 2025-04-10 08:36:39.352380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bbb72f6865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('minutes_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('rebounds_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('steals_per_game', sa.Float(), nullable=True),
    sa.Column('blocks_per_game', sa.Float(), nullable=True),
    sa.Column('turnovers_per_game', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('three_pm', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('stats_id')
    )
    op.create_index(op.f('ix_player_stats_stats_id'), 'player_stats', ['stats_id'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bbm_rank', sa.Float(), nullable=True),
    sa.Column('bbm_value', sa.Float(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('injury_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_player_stats_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
