"""add player_game_stats and team_schedule tables

Revision ID: ba0a5137c085
Revises: 93bbb72f6865
Create Date: 2025-04-14 11:51:01.785480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0a5137c085'
down_revision = '93bbb72f6865'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_stats',
    sa.Column('game_stats_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('opponent_team', sa.String(), nullable=True),
    sa.Column('home_or_away', sa.String(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('three_pm', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_stats_id')
    )
    op.create_index(op.f('ix_player_game_stats_game_stats_id'), 'player_game_stats', ['game_stats_id'], unique=False)
    op.create_table('team_schedule',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('opponent_team', sa.String(), nullable=True),
    sa.Column('home_or_away', sa.String(), nullable=True),
    sa.Column('game_time', sa.DateTime(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('is_back_to_back', sa.Boolean(), nullable=True),
    sa.Column('is_high_volume_day', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_team_schedule_game_id'), 'team_schedule', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_schedule_game_id'), table_name='team_schedule')
    op.drop_table('team_schedule')
    op.drop_index(op.f('ix_player_game_stats_game_stats_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    # ### end Alembic commands ###
