"""create player_features table

Revision ID: d8e2e8a9a71d
Revises: ba0a5137c085
Create Date: 2025-04-14 12:11:10.281836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e2e8a9a71d'
down_revision = 'ba0a5137c085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_features',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('z_points', sa.Float(), nullable=True),
    sa.Column('z_rebounds', sa.Float(), nullable=True),
    sa.Column('z_assists', sa.Float(), nullable=True),
    sa.Column('z_steals', sa.Float(), nullable=True),
    sa.Column('z_blocks', sa.Float(), nullable=True),
    sa.Column('z_turnovers', sa.Float(), nullable=True),
    sa.Column('z_fg_pct', sa.Float(), nullable=True),
    sa.Column('z_ft_pct', sa.Float(), nullable=True),
    sa.Column('z_three_pm', sa.Float(), nullable=True),
    sa.Column('total_z_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index(op.f('ix_player_features_feature_id'), 'player_features', ['feature_id'], unique=False)
    op.create_index(op.f('ix_player_features_player_id'), 'player_features', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_features_player_id'), table_name='player_features')
    op.drop_index(op.f('ix_player_features_feature_id'), table_name='player_features')
    op.drop_table('player_features')
    # ### end Alembic commands ###
